name: fdp/dev/westus

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app-infra/fdp/dev/westus/**'
  workflow_dispatch:
    inputs:
      tf-action:
        type: choice
        default: apply
        description: Apply/Destroy Infrastructure
        options: 
        - apply
        - destroy

jobs:

  infra-deploy:
    uses: briteliteimmersive/devops-automation-enablers/.github/workflows/tf-deploy.yml@main
    with:
      tf-module-name: 'app-infra'
      tf-module-version: '5.0.0'
      tf-vars-directory: 'fdp/dev/westus'
      tf-plan-gh-env: 'fedp-tf-plan-non-prod'
      tf-apply-gh-env: 'fedp-tf-apply-non-prod'
    secrets: inherit
